### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft-shop#6]
When requesting a new password, one gets a mail with:

> In order to choose a new password follow this link: https://saturn.uberspace.de
/f/login/new_password?id=4&token=tuxofrafundachuphaphutafongyxiquqefsuquy

Issues:
- https://saturn.uberspace.de ist clickable, the rest not
- In the admin interface of the foodsoft I have set the 'homepage' to a different URL. Therefore the link does not work.

**Comment by wvengen** [comment]
Hi, if this is a question about Foodsoft, you may want to open a bug in https://github.com/foodcoops/foodsoft/issues instead. This is about an experimental sub-component in development.

Anyway, regarding your question: is your mail client breaking the line? That may be a cause. I cannot reproduce it.

Regarding the homepage, this is the URL for the footer link, and redirect after logout. If you'd like to see a different URL in the mail, you need to change `config/app_config.yml` (or else `config/environments/production.rb`).
